language: elixir
elixir: '1.7.4'
otp_release: '21.1.4'

# http://blog.danielberkompas.com/elixir/2015/04/03/run-dialyzer-on-elixir-on-travis.html
# TODO This is temporarily disabled while it doesn't work
# before_script:
#   # Set download location
#   - export PLT_FILENAME=elixir-${TRAVIS_ELIXIR_VERSION}_${TRAVIS_OTP_RELEASE}.plt
#   - export PLT_LOCATION=/home/travis/$PLT_FILENAME
#   # Download PLT from danielberkompas/travis_elixir_plts on Github
#   # Store in $PLT_LOCATION
#   - wget -O $PLT_LOCATION https://raw.github.com/danielberkompas/travis_elixir_plts/master/$PLT_FILENAME

script:
  - export PROJECT_NAME=ex_structable
  - mix test
  - mix credo
  - mix coveralls.travis
  - mix format --check-formatted
#  - dialyzer --no_check_plt --plt $PLT_LOCATION --no_native _build/test/lib/$PROJECT_NAME/ebin
